language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.0
    - android-25

jdk:
  - oraclejdk8

script:
   - (while sleep 3; do echo "y"; done) | $ANDROID_HOME/tools/android update sdk -u
   - ./gradlew build
